In [1]:
import os
import nltk
import numpy as np
import random
import string
import re
import glob
from nltk.corpus import stopwords

path = "/Users/dipes/Documents/Senior Year/Natural Language Processing/Final Project/data/character/bad"

stop_words = set(stopwords.words('english')) 
#print(stop_words)

wordfreq={}
for filename in glob.glob(os.path.join(path, '*.txt')):
    input_file=open(filename, 'r')
    text=''
    for line in input_file:
        text += line
    
    characterfile=nltk.sent_tokenize(text)
    for i in range(len(characterfile)):
        characterfile[i]=characterfile[i].lower()
        characterfile[i]=re.sub(r'\W', ' ', characterfile[i])
        characterfile[i]=re.sub(r'\s+', ' ', characterfile[i])
    #print(len(characterfile))
    #print(characterfile[2])
    
    for sentence in characterfile:
        tokens = nltk.word_tokenize(sentence)
        for token in tokens:
            if token not in wordfreq.keys() and token not in stop_words:
                wordfreq[token] = 1
            elif token in wordfreq.keys() and token not in stop_words:
                wordfreq[token] +=1
    input_file.close()

import heapq
top=50
most_freq=heapq.nlargest(top, wordfreq, key=wordfreq.get)
print(most_freq)
    
wordsperchar = []
totalwords = []
numofcharacters = 0 

for filename in glob.glob(os.path.join(path, '*.txt')):
    input_file=open(filename, 'r')
    text=''
    for line in input_file:
        text += line
    
    characterfile=nltk.sent_tokenize(text)
    for i in range(len(characterfile)):
        characterfile[i]=characterfile[i].lower()
        characterfile[i]=re.sub(r'\W', ' ', characterfile[i])
        characterfile[i]=re.sub(r'\s+', ' ', characterfile[i])
    #print(len(characterfile))
    #print(characterfile[2])
    
    words=0
    sentence_vectors = []
    numofcharacters += 1 
    
    for sentence in characterfile:
        #print(sentence)
        #print(len(sentence))
        #print(len(sentence.split()))
        words += len(sentence.split())
        sentence_tokens=nltk.word_tokenize(sentence)
        sent_vec = []
        for token in most_freq:
            if token in sentence_tokens:
                sent_vec.append(1)
            else:
                sent_vec.append(0)
        sentence_vectors.append(sent_vec)
        
    averagesentence = np.sum(sentence_vectors)/len(sentence_vectors)
    averageword= np.sum(sentence_vectors)/words
    sentence_vectors = np.asarray(sentence_vectors)
    
    wordsperchar.append(np.sum(sentence_vectors))
    totalwords.append(words)
    
    #print(sentence_vectors)
    #print(np.sum(sentence_vectors), "of the ", top, "most frequent words are present")
    #print("There are ", len(sentence_vectors), "sentences")
    #print("There are ", words, "words for this character")
    #print("The average amount of the ", top, "most frequent words for bad characters present in each sentence for this character is: ", averagesentence)
    #print("The average amount of the ", top, "most frequent words for bad characters present per word for this character is: ", averageword)
    input_file.close()
    
print(wordsperchar)
print(numofcharacters)
print(totalwords)
print("The average number of top", top, "words per bad character is", np.sum(wordsperchar)/numofcharacters )
print("The average number of top", top, "words per total words (within all bad characters is)", np.sum(wordsperchar)/np.sum(totalwords))
    

    
    
    
path = "/Users/dipes/Documents/Senior Year/Natural Language Processing/Final Project/data/character/good"

wordsperchar = []
totalwords = []
numofcharacters = 0 

for filename in glob.glob(os.path.join(path, '*.txt')):
    input_file=open(filename, 'r')
    text=''
    for line in input_file:
        text += line
    
    characterfile=nltk.sent_tokenize(text)
    for i in range(len(characterfile)):
        characterfile[i]=characterfile[i].lower()
        characterfile[i]=re.sub(r'\W', ' ', characterfile[i])
        characterfile[i]=re.sub(r'\s+', ' ', characterfile[i])
    #print(len(characterfile))
    #print(characterfile[2])
    
    words=0
    sentence_vectors = []
    numofcharacters += 1 
    
    for sentence in characterfile:
        #print(sentence)
        #print(len(sentence))
        #print(len(sentence.split()))
        words += len(sentence.split())
        sentence_tokens=nltk.word_tokenize(sentence)
        sent_vec = []
        for token in most_freq:
            if token in sentence_tokens:
                sent_vec.append(1)
            else:
                sent_vec.append(0)
        sentence_vectors.append(sent_vec)
        
    averagesentence = np.sum(sentence_vectors)/len(sentence_vectors)
    averageword= np.sum(sentence_vectors)/words
    sentence_vectors = np.asarray(sentence_vectors)
    
    wordsperchar.append(np.sum(sentence_vectors))
    totalwords.append(words)
    
    print(sentence_vectors)
    print(np.sum(sentence_vectors), "of the ", top, "most frequent words (from bad characters) are present")
    print("There are ", len(sentence_vectors), "sentences")
    print("There are ", words, "words for this character")
    print("The average amount of the ", top, "most frequent words for bad characters present in each sentence for this good character is: ", averagesentence)
    print("The average amount of the ", top, "most frequent words for bad characters present per word for this good character is: ", averageword)
    input_file.close()
    
print(wordsperchar)
print(numofcharacters)
print(totalwords)
print("The average number of top", top, "words (from bad characters) per good character is", np.sum(wordsperchar)/numofcharacters )
print("The average number of top", top, "words (from bad characters) per total words (within all good characters is)", np.sum(wordsperchar)/np.sum(totalwords))
    


['know', 'get', 'going', 'got', 'yeah', 'one', 'right', 'like', 'look', 'want', 'never', 'okay', 'uh', 'help', 'hey', 'back', 'go', 'oh', 'yes', 'could', 'think', 'told', 'would', 'guy', 'mean', 'well', 'life', 'time', 'good', 'man', 'us', 'tell', 'take', 'come', 'two', 'even', 'let', 'see', 'wife', 'sure', 'something', 'anything', 'need', 'everything', 'little', 'came', 'day', 'dead', 'call', 'please']
[15, 17, 7, 2, 9, 4, 8, 24, 27, 29, 26, 13, 13, 7, 11, 27, 6, 11, 55, 10, 12, 44, 27, 26, 23, 42, 16, 7, 16, 8, 0, 7, 25, 8, 97, 14, 27, 41, 19, 54, 5, 41, 13, 26, 54, 15, 15, 26, 11, 28, 20]
51
[131, 120, 28, 18, 97, 17, 65, 269, 196, 311, 198, 77, 101, 34, 93, 211, 116, 95, 344, 116, 42, 379, 152, 262, 177, 421, 111, 68, 135, 61, 4, 31, 203, 83, 729, 130, 298, 394, 106, 446, 33, 304, 108, 243, 717, 162, 136, 206, 76, 286, 160]
The average number of top 50 words per bad character is 21.333333333333332
The average number of top 50 words per total words (within all bad characters is) 0.1

There are  22 sentences
There are  119 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.5454545454545454
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.10084033613445378
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
43 of the  50 most frequent words (from bad characters) are present
There are  78 sentences
There are  572 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.5512820512820513
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.07517482517482517
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
28 of the 

23 of the  50 most frequent words (from bad characters) are present
There are  35 sentences
There are  248 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.6571428571428571
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.09274193548387097
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
15 of the  50 most frequent words (from bad characters) are present
There are  23 sentences
There are  127 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.6521739130434783
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.11811023622047244
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
21 of the  50 most frequent words (from bad characters) are present
There are  78 sentences
There are  470 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.2692307692307692
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.04468085106382979
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
255 of the  50 most frequent words (from bad characters) are present
There are  382 sentences
There are  2567 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.6675392670157068
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.09933774834437085
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
227 of the  50 most frequent words (from bad characters) are present
There are  334 sentences
There are  2123 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.6796407185628742
The average amount of the  50 most frequent words for bad characters pr

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
16 of the  50 most frequent words (from bad characters) are present
There are  39 sentences
There are  200 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.41025641025641024
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.08
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
13 of the  50 most frequent words (from bad characters) are present
There are  24 sentences
There are  166 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.5416666666666666
The average amount of the  50 most frequent words for bad characters present per word for t

9 of the  50 most frequent words (from bad characters) are present
There are  12 sentences
There are  100 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.75
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.09
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
32 of the  50 most frequent words (from bad characters) are present
There are  44 sentences
There are  262 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.7272727272727273
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.12213740458015267
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ...

31 of the  50 most frequent words (from bad characters) are present
There are  35 sentences
There are  252 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.8857142857142857
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.12301587301587301
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
20 of the  50 most frequent words (from bad characters) are present
There are  35 sentences
There are  223 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.5714285714285714
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.08968609865470852
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...


13 of the  50 most frequent words (from bad characters) are present
There are  15 sentences
There are  111 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.8666666666666667
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.11711711711711711
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
1460 of the  50 most frequent words (from bad characters) are present
There are  2308 sentences
There are  13895 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.6325823223570191
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.1050737675422814
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]


5 of the  50 most frequent words (from bad characters) are present
There are  20 sentences
There are  232 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.25
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.021551724137931036
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
73 of the  50 most frequent words (from bad characters) are present
There are  101 sentences
There are  755 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.7227722772277227
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.09668874172185431
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0

105 of the  50 most frequent words (from bad characters) are present
There are  133 sentences
There are  1165 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.7894736842105263
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.09012875536480687
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
19 of the  50 most frequent words (from bad characters) are present
There are  41 sentences
There are  273 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.4634146341463415
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.0695970695970696
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ..

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
1433 of the  50 most frequent words (from bad characters) are present
There are  2042 sentences
There are  13400 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.7017629774730656
The average amount of the  50 most frequent words for bad characters present per word for this good character is:  0.10694029850746269
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
104 of the  50 most frequent words (from bad characters) are present
There are  154 sentences
There are  900 words for this character
The average amount of the  50 most frequent words for bad characters present in each sentence for this good character is:  0.6753246753246753
The average amount of the  50 most frequent words for bad characters 