In [ ]:
import os
import nltk
import numpy as np
import random
import string
import re
import glob
from nltk.corpus import stopwords

path = "/Users/dipes/Documents/Senior Year/Natural Language Processing/Final Project/data/character/good"

stop_words = set(stopwords.words('english')) 
#print(stop_words)

wordfreq={}
for filename in glob.glob(os.path.join(path, '*.txt')):
    input_file=open(filename, 'r')
    text=''
    for line in input_file:
        text += line
    
    characterfile=nltk.sent_tokenize(text)
    for i in range(len(characterfile)):
        characterfile[i]=characterfile[i].lower()
        characterfile[i]=re.sub(r'\W', ' ', characterfile[i])
        characterfile[i]=re.sub(r'\s+', ' ', characterfile[i])
    #print(len(characterfile))
    #print(characterfile[2])
    
    for sentence in characterfile:
        tokens = nltk.word_tokenize(sentence)
        for token in tokens:
            if token not in wordfreq.keys() and token not in stop_words:
                wordfreq[token] = 1
            elif token in wordfreq.keys() and token not in stop_words:
                wordfreq[token] +=1
    input_file.close()

import heapq
top=50
most_freq=heapq.nlargest(top, wordfreq, key=wordfreq.get)
print(most_freq)
    
    
for filename in glob.glob(os.path.join(path, '*.txt')):
    input_file=open(filename, 'r')
    text=''
    for line in input_file:
        text += line
    
    characterfile=nltk.sent_tokenize(text)
    for i in range(len(characterfile)):
        characterfile[i]=characterfile[i].lower()
        characterfile[i]=re.sub(r'\W', ' ', characterfile[i])
        characterfile[i]=re.sub(r'\s+', ' ', characterfile[i])
    #print(len(characterfile))
    #print(characterfile[2])
    
    words=0
    sentence_vectors = []
    for sentence in characterfile:
        #print(sentence)
        #print(len(sentence))
        #print(len(sentence.split()))
        words += len(sentence.split())
        sentence_tokens=nltk.word_tokenize(sentence)
        sent_vec = []
        for token in most_freq:
            if token in sentence_tokens:
                sent_vec.append(1)
            else:
                sent_vec.append(0)
        sentence_vectors.append(sent_vec)
        
    averagesentence = np.sum(sentence_vectors)/len(sentence_vectors)
    averageword= np.sum(sentence_vectors)/words
    sentence_vectors = np.asarray(sentence_vectors)
    
    print(sentence_vectors)
    print(np.sum(sentence_vectors), "of the ", top, "most frequent words are present")
    print("There are ", len(sentence_vectors), "sentences")
    print("There are ", words, "words for this character")
    print("The average amount of the ", top, "most frequent words for good characters present in each sentence for this character is: ", averagesentence)
    print("The average amount of the ", top, "most frequent words for good characters present per word for this character is: ", averageword)
    input_file.close()
    
#calculate average for good and bad characters using only the top 50 for good and then top 50 for bad
    
    

['know', 'got', 'yeah', 'well', 'like', 'right', 'one', 'get', 'going', 'see', 'hey', 'back', 'guy', 'okay', 'want', 'think', 'go', 'look', 'tell', 'would', 'uh', 'oh', 'found', 'time', 'us', 'let', 'good', 'take', 'two', 'could', 'blood', 'something', 'evidence', 'need', 'anything', 'grissom', 'man', 'crime', 'body', 'case', 'maybe', 'make', 'nick', 'mr', 'mean', 'find', 'dead', 'never', 'come', 'last']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
10 of the  50 most frequent words are present
There are  22 sentences
There are  135 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.45454545454545453
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.07407407407407407
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ...

The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.5909090909090909
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.1092436974789916
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
47 of the  50 most frequent words are present
There are  78 sentences
There are  572 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.6025641025641025
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.08216783216783216
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
26 of the  50 most frequent words are present
There are  68 sentences
There are  328 words for this character
The

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
22 of the  50 most frequent words are present
There are  35 sentences
There are  248 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.6285714285714286
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.08870967741935484
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
13 of the  50 most frequent words are present
There are  23 sentences
There are  127 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.5652173913043478
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.10236220472440945
[[

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
19 of the  50 most frequent words are present
There are  78 sentences
There are  470 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.24358974358974358
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.04042553191489362
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
274 of the  50 most frequent words are present
There are  382 sentences
There are  2567 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.7172774869109948
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.10673938449552006
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
245 of the  50 most frequent words are present
There are  334 sentences
There are  2123 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.7335329341317365
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.11540273198304

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
22 of the  50 most frequent words are present
There are  48 sentences
There are  316 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.4583333333333333
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.06962025316455696
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
39 of the  50 most frequent words are present
There are  68 sentences
There are  437 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.5735294117647058
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.08924485125858124
[[

  0 0 0 0 0 1 0 0 0 0 0 0 0 0]]
14 of the  50 most frequent words are present
There are  16 sentences
There are  114 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.875
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.12280701754385964
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0

[[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0

The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.6216216216216216
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.09745762711864407
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
1603 of the  50 most frequent words are present
There are  2436 sentences
There are  15579 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.6580459770114943
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.10289492265228833
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
44 of the  50 most frequent words are present
There are  49 sentences
There are  356 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this character is:  0.8979591836734694
The average amount of the  50 most frequent words for good characters present per word for this character is:  0.12359550561797