In [3]:
import os
import nltk
import numpy as np
import random
import string
import re
import glob
from nltk.corpus import stopwords

path = "/Users/dipes/Documents/Senior Year/Natural Language Processing/Final Project/data/character/bad"

stop_words = set(stopwords.words('english')) 
#print(stop_words)

wordfreq={}
for filename in glob.glob(os.path.join(path, '*.txt')):
    input_file=open(filename, 'r')
    text=''
    for line in input_file:
        text += line
    
    characterfile=nltk.sent_tokenize(text)
    for i in range(len(characterfile)):
        characterfile[i]=characterfile[i].lower()
        characterfile[i]=re.sub(r'\W', ' ', characterfile[i])
        characterfile[i]=re.sub(r'\s+', ' ', characterfile[i])
    #print(len(characterfile))
    #print(characterfile[2])
    
    for sentence in characterfile:
        tokens = nltk.word_tokenize(sentence)
        for token in tokens:
            if token not in wordfreq.keys() and token not in stop_words:
                wordfreq[token] = 1
            elif token in wordfreq.keys() and token not in stop_words:
                wordfreq[token] +=1
    input_file.close()

import heapq
top=50
most_freq=heapq.nlargest(top, wordfreq, key=wordfreq.get)
print(most_freq)
    
    
for filename in glob.glob(os.path.join(path, '*.txt')):
    input_file=open(filename, 'r')
    text=''
    for line in input_file:
        text += line
    
    characterfile=nltk.sent_tokenize(text)
    for i in range(len(characterfile)):
        characterfile[i]=characterfile[i].lower()
        characterfile[i]=re.sub(r'\W', ' ', characterfile[i])
        characterfile[i]=re.sub(r'\s+', ' ', characterfile[i])
    #print(len(characterfile))
    #print(characterfile[2])
    
    sentence_vectors = []
    for sentence in characterfile:
        sentence_tokens=nltk.word_tokenize(sentence)
        sent_vec = []
        for token in most_freq:
            if token in sentence_tokens:
                sent_vec.append(1)
            else:
                sent_vec.append(0)
        sentence_vectors.append(sent_vec)
        
    average = np.sum(sentence_vectors)/len(sentence_vectors)
    sentence_vectors = np.asarray(sentence_vectors)
    print(sentence_vectors)
    print(np.sum(sentence_vectors), "of the ", top, "most frequent words are present")
    print("There are ", len(sentence_vectors), "sentences")
    print("The average amount of the ", top, "most frequent words for bad characters present in each sentence for this character is: ", average)
    input_file.close()
    

['know', 'get', 'going', 'got', 'yeah', 'one', 'right', 'like', 'look', 'want', 'never', 'okay', 'uh', 'help', 'hey', 'back', 'go', 'oh', 'yes', 'could', 'think', 'told', 'would', 'guy', 'mean', 'well', 'life', 'time', 'good', 'man', 'us', 'tell', 'take', 'come', 'two', 'even', 'let', 'see', 'wife', 'sure', 'something', 'anything', 'need', 'everything', 'little', 'came', 'day', 'dead', 'call', 'please']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
15 of the  50 most frequent words are present
There are  21 sentences
The average amount of the  50 most frequent words for bad characters present in each sentence for this character is:  0.7142857142857143
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

 [0 0 0 ... 0 0 0]]
16 of the  50 most frequent words are present
There are  23 sentences
The average amount of the  50 most frequent words for bad characters present in each sentence for this character is:  0.6956521739130435
[[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

20 of the  50 most frequent words are present
There are  30 sentences
The average amount of the  50 most frequent words for bad characters present in each sentence for this character is:  0.6666666666666666
