In [6]:
import os
import nltk
import numpy as np
import random
import string
import re
import glob
from nltk.corpus import stopwords

path = "/Users/dipes/Documents/Senior Year/Natural Language Processing/Final Project/data/character/good"

stop_words = set(stopwords.words('english')) 
#print(stop_words)

wordfreq={}
for filename in glob.glob(os.path.join(path, '*.txt')):
    input_file=open(filename, 'r')
    text=''
    for line in input_file:
        text += line
    
    characterfile=nltk.sent_tokenize(text)
    for i in range(len(characterfile)):
        characterfile[i]=characterfile[i].lower()
        characterfile[i]=re.sub(r'\W', ' ', characterfile[i])
        characterfile[i]=re.sub(r'\s+', ' ', characterfile[i])
    #print(len(characterfile))
    #print(characterfile[2])
    
    for sentence in characterfile:
        tokens = nltk.word_tokenize(sentence)
        for token in tokens:
            if token not in wordfreq.keys() and token not in stop_words:
                wordfreq[token] = 1
            elif token in wordfreq.keys() and token not in stop_words:
                wordfreq[token] +=1
    input_file.close()

import heapq
top=50
most_freq=heapq.nlargest(top, wordfreq, key=wordfreq.get)
print(most_freq)
    
wordsperchar = []
totalwords = []
numofcharacters = 0 

for filename in glob.glob(os.path.join(path, '*.txt')):
    input_file=open(filename, 'r')
    text=''
    for line in input_file:
        text += line
    
    characterfile=nltk.sent_tokenize(text)
    for i in range(len(characterfile)):
        characterfile[i]=characterfile[i].lower()
        characterfile[i]=re.sub(r'\W', ' ', characterfile[i])
        characterfile[i]=re.sub(r'\s+', ' ', characterfile[i])
    #print(len(characterfile))
    #print(characterfile[2])
    
    words=0
    sentence_vectors = []
    numofcharacters += 1 
    
    for sentence in characterfile:
        #print(sentence)
        #print(len(sentence))
        #print(len(sentence.split()))
        words += len(sentence.split())
        sentence_tokens=nltk.word_tokenize(sentence)
        sent_vec = []
        for token in most_freq:
            if token in sentence_tokens:
                sent_vec.append(1)
            else:
                sent_vec.append(0)
        sentence_vectors.append(sent_vec)
        
    averagesentence = np.sum(sentence_vectors)/len(sentence_vectors)
    averageword= np.sum(sentence_vectors)/words
    sentence_vectors = np.asarray(sentence_vectors)
    
    wordsperchar.append(np.sum(sentence_vectors))
    totalwords.append(words)
    
    #print(sentence_vectors)
    #print(np.sum(sentence_vectors), "of the ", top, "most frequent words are present")
    #print("There are ", len(sentence_vectors), "sentences")
    #print("There are ", words, "words for this character")
    #print("The average amount of the ", top, "most frequent words for good characters present in each sentence for this character is: ", averagesentence)
    #print("The average amount of the ", top, "most frequent words for good characters present per word for this character is: ", averageword)
    input_file.close()
    
print(wordsperchar)
print(numofcharacters)
print(totalwords)
print("The average number of top", top, "words per good character is", np.sum(wordsperchar)/numofcharacters )
print("The average number of top", top, "words per total words (within all good characters is)", np.sum(wordsperchar)/np.sum(totalwords))
    

    
    
    
path = "/Users/dipes/Documents/Senior Year/Natural Language Processing/Final Project/data/character/bad"

wordsperchar = []
totalwords = []
numofcharacters = 0 

for filename in glob.glob(os.path.join(path, '*.txt')):
    input_file=open(filename, 'r')
    text=''
    for line in input_file:
        text += line
    
    characterfile=nltk.sent_tokenize(text)
    for i in range(len(characterfile)):
        characterfile[i]=characterfile[i].lower()
        characterfile[i]=re.sub(r'\W', ' ', characterfile[i])
        characterfile[i]=re.sub(r'\s+', ' ', characterfile[i])
    #print(len(characterfile))
    #print(characterfile[2])
    
    words=0
    sentence_vectors = []
    numofcharacters += 1 
    
    for sentence in characterfile:
        #print(sentence)
        #print(len(sentence))
        #print(len(sentence.split()))
        words += len(sentence.split())
        sentence_tokens=nltk.word_tokenize(sentence)
        sent_vec = []
        for token in most_freq:
            if token in sentence_tokens:
                sent_vec.append(1)
            else:
                sent_vec.append(0)
        sentence_vectors.append(sent_vec)
        
    averagesentence = np.sum(sentence_vectors)/len(sentence_vectors)
    averageword= np.sum(sentence_vectors)/words
    sentence_vectors = np.asarray(sentence_vectors)
    
    wordsperchar.append(np.sum(sentence_vectors))
    totalwords.append(words)
    
    print(sentence_vectors)
    print(np.sum(sentence_vectors), "of the ", top, "most frequent words (from good characters) are present")
    print("There are ", len(sentence_vectors), "sentences")
    print("There are ", words, "words for this character")
    print("The average amount of the ", top, "most frequent words for good characters present in each sentence for this bad character is: ", averagesentence)
    print("The average amount of the ", top, "most frequent words for good characters present per word for this bad character is: ", averageword)
    input_file.close()
    
print(wordsperchar)
print(numofcharacters)
print(totalwords)
print("The average number of top", top, "words (from good characters) per bad character is", np.sum(wordsperchar)/numofcharacters )
print("The average number of top", top, "words (from good characters) per total words (within all bad characters is)", np.sum(wordsperchar)/np.sum(totalwords))
    


['know', 'got', 'yeah', 'well', 'like', 'right', 'one', 'get', 'going', 'see', 'hey', 'back', 'guy', 'okay', 'want', 'think', 'go', 'look', 'tell', 'would', 'uh', 'oh', 'found', 'time', 'us', 'let', 'good', 'take', 'two', 'could', 'blood', 'something', 'evidence', 'need', 'anything', 'grissom', 'man', 'crime', 'body', 'case', 'maybe', 'make', 'nick', 'mr', 'mean', 'find', 'dead', 'never', 'come', 'last']
[10, 71, 7, 14, 7, 22, 32, 23, 24, 13, 47, 26, 11, 1083, 18, 20, 2236, 82, 33, 16, 26, 18, 11, 78, 22, 13, 58, 12, 12, 40, 33, 24, 15, 126, 131, 11, 71, 19, 6, 34, 22, 11, 2, 17, 18, 71, 12, 217, 274, 245, 3152, 15, 19, 25, 41, 123, 12, 28, 17, 16, 18, 27, 29, 22, 39, 11, 27, 16, 12, 27, 71, 10, 34, 20, 22, 31, 17, 22, 7, 41, 65, 13, 13, 4, 14, 8, 33, 12, 26, 30, 17, 20, 18, 14, 24, 27, 28, 16, 23, 13, 27, 12, 10, 6, 19, 17, 15, 1598, 98, 8, 41, 8, 11, 10, 15, 23, 6, 70, 15, 11, 10, 39, 16, 24, 185, 12, 33, 22, 29, 1603, 44, 3, 21, 15, 67, 27, 120, 19, 19, 58, 27, 21, 26, 26, 15, 23, 1

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
25 of the  50 most frequent words (from good characters) are present
There are  46 sentences
There are  311 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this bad character is:  0.5434782608695652
The average amount of the  50 most frequent words for good characters present per word for this bad character is:  0.08038585209003216
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
24 of the  50 most frequent words (from good characters) are present
There are  38 sentences
There are  198 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this bad character is:  0.631578947368421
The average amount of the  50 most frequent words for good characters presen

The average amount of the  50 most frequent words for good characters present per word for this bad character is:  0.0603448275862069
[[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 

  0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
6 of the  50 most frequent words (from good characters) are present
There are  15 sentences
There are  68 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this bad character is:  0.4
The average amount of the  50 most frequent words for good characters present per word for this bad character is:  0.08823529411764706
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
14 of the  50 most frequent words (from good characters) are present
There are  23 sentences
There are  135 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this bad character is:  0.6086956521739131
The average amount of the  50 most frequent words for good characters present per word for this bad character is:  0.1037037037037037
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
45 of the  50 most frequent words (from good characters) are present
There are  81 sentences
There are  446 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this bad character is:  0.5555555555555556
The average amount of the  50 most frequent words for good characters present per word for this bad character is:  0.10089686098654709
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

There are  30 sentences
There are  160 words for this character
The average amount of the  50 most frequent words for good characters present in each sentence for this bad character is:  0.5666666666666667
The average amount of the  50 most frequent words for good characters present per word for this bad character is:  0.10625
[11, 15, 7, 2, 9, 3, 9, 22, 25, 25, 24, 12, 11, 2, 11, 13, 7, 10, 53, 8, 4, 40, 18, 26, 21, 40, 16, 6, 14, 5, 0, 7, 25, 8, 95, 18, 25, 32, 16, 45, 4, 38, 10, 26, 57, 17, 16, 16, 8, 20, 17]
51
[131, 120, 28, 18, 97, 17, 65, 269, 196, 311, 198, 77, 101, 34, 93, 211, 116, 95, 344, 116, 42, 379, 152, 262, 177, 421, 111, 68, 135, 61, 4, 31, 203, 83, 729, 130, 298, 394, 106, 446, 33, 304, 108, 243, 717, 162, 136, 206, 76, 286, 160]
The average number of top 50 words (from good characters) per bad character is 19.0
The average number of top 50 words (from good characters) per total words (within all bad characters is) 0.10419354838709677
